### ISSUE TITLE
Missing description

### ISSUE THREAD

**Issue by explainer** [patcito/angularjs_scaffold#2]
I can follow the installation up to the point where the Posts scaffold is done.  From that point, I cannot determine how the Post views should be invoked.  I get nothing.  Is it necessary to edit application.html.erb to add my own links in the menus?  There is no joy here in Mudville.

**Comment by patcito** [comment]
Did you start the app and opened http://localhost:3000/posts? Does it show something?

**Comment by explainer** [comment]
Here is what I did:
1. rails new sudoku
2. cd sudoku
3. edit Gemfile, add " gem 'angularjs_scaffold' "
4. bundle install
5. rails g angularjs:install
6. rails g scaffold Post title:string body:string
   rake db:migrate
7. rails g angularjs:scaffold Posts
8. edit seed.rb file, added 2 Post.create(title: 'post 1', body: 'some
   content) ,  like so.
9. rails server
10. http://localhost:3000/posts
11. I get the contents of application.html.erb displayed, showing the
    main menu and the sidebar menu, but no posts...

On 23 October 2012 15:46, Patrick Aljord notifications@github.com wrote:

> Did you start the app and opened http://localhost:3000/posts? Does it
> show something?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/patcito/angularjs_scaffold/issues/2#issuecomment-9721331.

## 

Regards,

Ken

Seek wisdom through disbelief

**Comment by patcito** [comment]
Do you have JS enabled?

edit: I just tried all these steps locally and it worked fine.

**Comment by explainer** [comment]
Hi Patrick,

I think I had a brain-fade or something, but the app now shows the Posts.

I do have another problem:  I get errors in my rails log file regarding:

Started GET "/assets/img/glyphicons-halflings.png" for 127.0.0.1 at
2012-10-24 09:29:16 -0700
Served asset /img/glyphicons-halflings.png - 404 Not Found (8ms)

ActionController::RoutingError (No route matches [GET]
"/assets/img/glyphicons-halflings.png"):

I think this is associated with Bootstrap, so maybe I should try an install
of angularjs_scaffold WITHOUT Bootstrap and font-awesome?  You mentioned
there was an option, but you did not specify what the option is...

On 24 October 2012 02:00, Patrick Aljord notifications@github.com wrote:

> Do you have JS enabled?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/patcito/angularjs_scaffold/issues/2#issuecomment-9732388.

## 

Regards,

Ken

Seek wisdom through disbelief

**Comment by patcito** [comment]
That's just a regular bootstrap/rails assets error.
