### ISSUE TITLE
Please reject my pull request

### ISSUE THREAD

**Issue by explainer** [patcito/angularjs_scaffold#7]
Hi Patrick,

I am a newbie with github pull requests, and I don't know how to dump my existing pull request in order to replace it with a new one, :-(

Would you reject my existing pull request?  I will then issue a new pull, which adds, among other things, an option to select either CoffeeScript or javascript when installing the generator.

Because the file routes.coffee.erb (routes.js.erb) accumulates routing information with each scaffold command used, the choice of language must be viewed as an application-wide decision.

**Comment by patcito** [comment]
ok
